

#配置dev环境
spring:
  profiles: dev
  application:
    name: eurekaServer-config
server:
  port: 8000

eureka:
  instance:
    hostname: eureka8000 #指定Eureka主机
  client:
    register-with-eureka: false #指定注册到Eureka server，因为本机是server，不是client
    fetch-registry: false #指定当前主机是否获取注册信息，因为本机是server，不是client
    service-url:
      #defaultZone: http://localhost:8000/eureka,http://localhost:8100/eureka,http://localhost:8200/eureka
      defaultZone: http://localhost:8000/eureka



---
#配置test环境
spring:
  profiles: test
  application:
    name: eurekaServer-config
server:
  port: 8100

eureka:
  instance:
    hostname: eureka8000 #指定Eureka主机
  client:
    register-with-eureka: false #指定注册到Eureka server，因为本机是server，不是client
    fetch-registry: false #指定当前主机是否获取注册信息，因为本机是server，不是client
    service-url:
      #defaultZone: http://localhost:8000/eureka,http://localhost:8100/eureka,http://localhost:8200/eureka
      defaultZone: http://localhost:8100/eureka